version: '3'
services:
  api:
    image: macostrans/data-generator-api:v1
    volumes:
      - ./src:/usr/src/app
    command: uvicorn main:app --host=0.0.0.0 --port 80
    deploy:
      replicas: 2
    #  constraints: [node.role==worker]
    networks:
      - frontend
    #   placement:
    #    constraints: [node.role == manager]
    # command: ["tail", "-f", "/dev/null"]
    ports:
      - "80:80"
networks:
  frontend: {}